apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - name: express-app
        image: node:22
        ports:
        - containerPort: 3000
        command: ["node", "/usr/src/app/app.js"]
        workingDir: /usr/src/app
        volumeMounts:
        - name: app-code
          mountPath: /usr/src/app
      volumes:
      - name: app-code
        configMap:
          name: express-app-code
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: express-app-code
  namespace: default
data:
  app.js: |
    const express = require('express');
    const app = express();
    const port = 3000;
    app.get('/', (req, res) => {
      res.send('Hello, DevOps!');
    });
    app.listen(port, () => {
      console.log(`Server running at http://localhost:${port}`);
    });
---
apiVersion: v1
kind: Service
metadata:
  name: express-app-service
  namespace: default
spec:
  selector:
    app: express-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
  type: ClusterIP